# Generated by Django 6.0.4 on 2026-04-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=255)),
                ('pull_number', models.PositiveIntegerField()),
                ('pr_url', models.URLField(blank=True)),
                ('user_context', models.TextField(blank=True)),
                ('changed_lines_payload', models.JSONField(default=list)),
                ('prompt_sent', models.TextField()),
                ('raw_ai_output', models.JSONField(blank=True, null=True)),
                ('normalized_findings', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
